### ISSUE TITLE
KeyError:'voltage'

### ISSUE THREAD

**Issue by zhangzee1999** [ognjenkundacina/graph-neural-network-state-estimation#2]
![image](https://github.com/ognjenkundacina/graph-neural-network-state-estimation/assets/75313890/4a8e732f-f4f1-4ba2-84b1-1f906847937a)
There is a problem, when I run train.py.

**Comment by ognjenkundacina** [comment]
Hello. Can you give more details step by step how to reproduce this? Are you running the code with your own dataset or with the example provided in this repository? Have you made any modifications to the code?

**Comment by zhangzee1999** [comment]
I didn't change any code. when I test this program, the first py file generate_networkx_graphs.py can run directedly. but, the train.py can't run correctly.

**Comment by ognjenkundacina** [comment]
There was a problem in the generate_networkx_graphs.py, I've pushed the fix. Please let me know if it works correctly now.

**Comment by zhangzee1999** [comment]
Thank you very much. Now, I've run this program and there is no problem for now.
